name: "Cremalink for Home-Assistant"
url: "https://github.com/ProfessorQuantumUniverse/cremalink-ha"
maintainer: "ProfessorQuantumUniverse"
source: "https://github.com/ProfessorQuantumUniverse/cremalink-ha"
homeassistant: "2026.1.0"
